---
- name: Get Homebrew path
  ansible.builtin.shell:
    cmd: brew --prefix  
  register: homebrew_prefix
- name: Install bash using Homebrew
  community.general.homebrew:
    name: bash 
    state: present
- name: Get name of user running the Ansible playbook 
  ansible.builtin.shell:
    cmd: whoami
  register: non_root_user 
- name: Print homebrew prefix
  debug:
    msg: "{{ homebrew_prefix.stdout }}"
- name: Print name of user running the Ansible playbook
  debug:
    msg: "{{ non_root_user.stdout }}"
- name: Make bash the default shell for the user running the playbook 
  become: yes
  user:
    name: "{{ non_root_user.stdout }}"
    shell: "{{ homebrew_prefix.stdout }}/bin/bash"
