#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
PLUGINS_DIR="plugins"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive

PLUGINS=""
for plugin in "$PLUGINS_DIR/"*
do
	PLUGINS+="--plugin-dir $plugin "
done


"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
	-d "${BASEDIR}" \
	-c "${CONFIG}" \
	$PLUGINS \
	"${@}"
