#!/usr/bin/env bash

set -e

# Get name of directory where this script is located
# and cd into it
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${BASEDIR}"

# Download all submodules 
git submodule update --init --recursive

# Create Python3 virtual env
if ! [[ -d .venv ]]; then
  python3 -m venv .venv
fi

# Activate virtual env
. .venv/bin/activate

# Install Python dependencies
python3 -m pip install -r requirements.txt

# Check that ansible is working
ansible --version

# Run bootstrap playbook
ansible-playbook bootstrap.yml

# Install Homebrew
#/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
