---
- name: Install homebrew pre-reqs on Debian/Ubuntu
  ansible.builtin.apt:
    name:
      - build-essential
      - procps
      - curl 
      - file
      - git
    state: present
  become: true 
