---
- name: Ensure vim autoload directory exists
  file:
    path: "{{ ansible_env.HOME }}/.vim/autoload"
    state: directory
    recurse: yes
    mode: 0700
- name: Download vim-plug into autoload directory
  ansible.builtin.get_url:
    dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
    force: false
    mode: '0700'
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/{{ vim_plug_version }}/plug.vim"
- name: Install shellcheck
  include_role:
    name: shellcheck
- name: Install bash-language-server
  include_role:
    name: bash-language-server
- name: Install terraform language server
  ansible.builtin.include_role:
    name: terraform-ls
- name: Find absolute path to vim conf file 
  find:
    paths: "{{ role_path }}/files"
    patterns: "vimrc"
  register: found_vimrc_file
- name: Symlink vimrc file
  file:
    src: "{{ found_vimrc_file.files[0].path }}"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    state: link
- name: Install all vim plugins specified in vimrc
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      vim -c ':PlugInstall' -c ':qall'
- name: Find absolute path to coc-nvim conf file
  find:
    paths: "{{ role_path }}/files"
    patterns: "coc-settings.json"
  register: found_coc_file
- name: Symlink coc-nvim config file
  file:
    src: "{{ found_coc_file.files[0].path }}"
    dest: "{{ ansible_env.HOME }}/.vim/coc-settings.json"
    state: link
- name: Install coc extensions
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      vim -c ':CocInstall -sync {{ item }} | qall'
  loop:
    - "coc-pyright"
    - "@yaegassy/coc-ansible"
